workflows:
  flutter-app:
    name: Labour Connect Full App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      java: 17
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - build/
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Analyze project
        script: flutter analyze
      - name: Run tests
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com
