packages:
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dev"
    source: hosted
    version: "6.1.2"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "1.2.2"
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      url: "https://pub.dev"
    source: hosted
    version: "3.6.0"
  firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      url: "https://pub.dev"
    source: hosted
    version: "5.3.2"
  cloud_firestore:
    dependency: "direct main"
    description:
      name: cloud_firestore
      url: "https://pub.dev"
    source: hosted
    version: "5.4.4"
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      url: "https://pub.dev"
    source: hosted
    version: "15.1.2"
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.dev"
    source: hosted
    version: "11.0.0"
  geocoding:
    dependency: "direct main"
    description:
      name: geocoding
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
  camera:
    dependency: "direct main"
    description:
      name: camera
      url: "https://pub.dev"
    source: hosted
    version: "0.11.0+2"
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dev"
    source: hosted
    version: "1.1.2"
  charts_flutter:
    dependency: "direct main"
    description:
      name: charts_flutter
      url: "https://pub.dev"
    source: hosted
    version: "0.12.0"
